var param={
    chanpintype:"骑马钉",
    cailiao:"",
    zidingyi:false,//true
    rule:"120mm*130mm",//{chang:100,duan:20}
    num:10,
    fengpi:{
        cailiao:{select:"11",yinse:"单黑",yinmian:"双面"},
        gongyi:[
            {fengmian:true},
            {yamo:true},
            {yawen:true,select:"liwen"},
            {jitu:true,list:[{chang:100,duan:50}]},
            {UV:true,list:[{select:"厚UV",chang:100,duan:50}]},
        ],
    },
    neiye:[
        {select:"",yinse:"",pshu:"",yesorno:""},
        {select:"",yinse:"",pshu:"",yesorno:""},
    ],
    files:[{key:"nnn.jpg"},{key:"nnn.jpg"}],
    modules:[{key:"nnn.jpg"},{key:"nnn.jpg"}],
    order:{
        type:1,//1邮寄2自提
        person:{name:"",phone:"",youbian:"31000"},
        sheng:"安徽省",
        shi:"淮北市",
        xian:"濉溪县",
        address:"到付件看来大家发老师的看法"
    }
}
